### ISSUE TITLE
no gemc build / gemc version

### ISSUE THREAD

**Issue by maureeungaro** [JeffersonLab/clas12-validation#146]
- [ ] no need to test gemc build as it's in clas12Tags CI
- [x] when triggered from clas12Tags it should use module load gemc/dev
- [x] when triggered from coatjava it should use module load gemc
- [x] if triggered from a PR from clas12-config with changes in the directory gemc/dev it should  use module load gemc/dev. Any other directory changes should use module load gemc

**Comment by c-dilks** [comment]
I disabled our nightly validation test here, til we can get this resolved, so we have one more TODO:
- [ ] re-enable nightly validation (if we still want it)
